name: test CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '^r[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: loop
        run: |
          for ros_distro in kinetic noetic; do
            for v in a b; do
              echo "${ros_distro} ${v}"
            done
          done
