name: test CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '^r[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
